version: "3"
services:
  elasticsearch:
    image: 'elasticsearch:6.4'
    hostname: elastic
    container_name: es-node
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 2048M
    tty: true
    privileged: true
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
        - elastic-stack

  kibana:
    image: 'kibana:6.4'
    hostname: kibana
    container_name: kibana_node
    tty: true
    privileged: true
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_IP=elasticsearch
    depends_on:
      - elasticsearch
    networks:
        - elastic-stack

  logstash:
    image: 'logstash:6.4'
    hostname: logstash
    container_name: log_node
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 2048M
    tty: true
    privileged: true
    ports:
      - '5044:5044'
    environment:
      - ELASTICSEARCH_IP=elasticsearch
    depends_on:
      - elasticsearch
    networks:
        - elastic-stack

networks:
    elastic-stack:
      driver: bridge