version: "3"
services:
  elasticsearch:
    image: 'elasticsearch:6.4'
    hostname: elastic
    tty: true
    privileged: true
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
        - internal

networks:
    internal:
      driver: bridge